version: "2"
services:
  nodeapp:
    container_name: node
    image: node:lts-stretch-slim
    ports:
      - "3000:3000"
    working_dir: /nodeapp
    volumes:
      - ./nodeapp:/nodeapp
    depends_on:
      - postgres
    environment:
        DB_HOST: postgres
        DATABASE_URL: postgres://admin:123456@postgres:5432/db_rest
        NODE_ENV: development
        PORT: 3000
    command: >
        bash -c "pwd
        && npm install express --save
        && npm install nodemon --save-dev
        && npm start"

  postgres:
    container_name: postgres
    image: postgres:9.6.13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_rest
    volumes:
      - ../db_rest:/var/lib/postgres
