version: "2"
services:
  react:
    container_name: nodeapp
    image: node:lts-stretch-slim
    ports:
      - "3010:3010"
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
        NODE_ENV: development
        PORT: 3010
    command: >
        bash -c "pwd
        && npm run dev -- -p 3010"
