version: "3.1"

networks:
    app-tier:
        driver: bridge

services:
  api:
    container_name: node
    image: node:lts-stretch-slim
    networks:
        - app-tier
    ports:
      - "3000:3000"
    working_dir: /nodeapp
    volumes:
      - ./nodeapp:/nodeapp
    depends_on:
      - mysqlserver
    environment:
        DB_HOSTNAME: mysqlserver
        NODE_ENV: development
        PORT: 3000
    command: >
        bash -c "pwd
        && npm start"


  mysqlserver:
    container_name: mysql_rest
    networks:
        - app-tier
    image: mariadb:10.4.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_rest
    ports:
      - "3306:3306"
    volumes:
      - ./db_rest:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin_rest
    image: phpmyadmin/phpmyadmin:4.7
    networks:
        - app-tier
    environment:
      PMA_HOST: mysqlserver
      PMA_PORT: 3306
    ports:
      - "4000:80"
    depends_on:
      - mysqlserver
    volumes:
      - ./conf/conf.php:/etc/phpmyadmin/config.user.inc.php
