version: "2"
services:
  nodeapp:
    container_name: node
    image: node:lts-stretch-slim
    ports:
      - "3000:3000"
    working_dir: /nodeapp
    volumes:
      - ./nodeapp:/nodeapp
    depends_on:
      - mysqlserver
    environment:
        MYSQL_HOST: mysqlserver
        DB_HOST: mysqlserver
        NODE_ENV: development
        PORT: 3000
    command: >
        bash -c "pwd
        && npm install express --save
        && npm install nodemon --save-dev
        && npm install mysql
        && npm start"


  mysqlserver:
    container_name: mysql_rest
    image: mysql:8.0.16
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123465
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_rest
    ports:
      - "3306:3306"
    volumes:
      - ./db_rest:/var/lib/mysql
      # - ./db/startup:/docker-entrypoint-initdb.d

  phpmyadmin:
    container_name: phpmyadmin_rest
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USE: admin
      MYSQL_ROOT_PASSWORD: 123456
      PMA_HOST: mysqlserver
      PMA_PORT: 3306
    ports:
      - "9000:80"
    depends_on:
      - mysqlserver
    volumes:
      - ./conf/conf.php:/etc/phpmyadmin/config.user.inc.php
